# Site settings
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "GridSide"
theme = "grid-side"

[params]

    #
    # Provide your name, description, and email that you want to include on
    # the main image of the main page.
    #
    name = "Your name"
    description = "Your description"
    email = "your@email.com"

    #
    # Contains the main grid cell of your site (such as a picture of yourself)
    # along with your name, description, and email. Any empty field will
    # not be included. Not providing an image will use a color. Marking as
    # disabled results in this cell not appearing in the site.
    #
    [params.header]

        name = "Your name"
        description = "Your description"
        email = "your@email.com"
        image = "profile.png"
        #color = "#FFF"
        #enabled = false

    #
    # Contains the cells representing the sections of your website. Each cell
    # contains the name of the cell, a brief description, and a link to the
    # associated section. 
    #
    # Not providing an image will use the color specified by 'color' as the
    # background color (default to #FFF).
    #
    # You can embed an icon using 'icon' to specify the classes to use
    # for the icon (such as 'fa fa-flag' when using font awesome).
    #
    # By default, each cell has a grid size of 1/3 (4 out of 12) for large
    # screens, 1/2 (6 out of 12) for medium screens, and 1 (12 out of 12) for
    # small screens. To change the cell's size per screen, use the properties
    # 'cell_large', 'cell_medium', and 'cell_small' respectively with a number
    # ranging from 1 to 12. Make sure that cells have nubmers equalling 12
    # per row.
    #
    [params.cells]

        [[params.cells.list]]

            name = "Blog"
            description = "Your personal blog"
            link = "/blog/"
            image = "blog.png"
            #color = "#FFF"
            #cell_large = 4
            #cell_medium = 6
            #cell_small = 12

        [[params.cells.list]]

            name = ""
            description = ""
            link = ""
            image = ""
            #color = "#FFF"
            #cell_large = 4
            #cell_medium = 6
            #cell_small = 12

        [[params.cells.list]]

            name = ""
            description = ""
            link = ""
            image = ""
            #color = "#FFF"
            #cell_large = 4
            #cell_medium = 6
            #cell_small = 12

        [[params.cells.list]]

            name = ""
            description = ""
            link = ""
            image = ""
            #color = "#FFF"
            #cell_large = 4
            #cell_medium = 6
            #cell_small = 12

        [[params.cells.list]]

            name = ""
            description = ""
            link = ""
            image = ""
            #color = "#FFF"
            #cell_large = 4
            #cell_medium = 6
            #cell_small = 12

        [[params.cells.list]]

            name = ""
            description = ""
            link = ""
            image = ""
            #color = "#FFF"
            #cell_large = 4
            #cell_medium = 6
            #cell_small = 12

